sonar.projectKey=go-project

sonar.sources=.
sonar.exclusions=**/*_test.go

sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.host.url=http://localhost:9000
sonar.login=sqp_856e74d2182672b8fa895a3b0ab8ed346822bcfb
sonar.go.coverage.reportPaths=coverage.out